name: Publish to rubygems

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Setup Rubygems
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        bash .github/setup-rubygems.sh
    - name: Publish to Rubygems
      run: |
        gem build marketplace_opportunity_scraper.gemspec
        gem push "marketplace_opportunity_scraper-$(git describe --tags).gem"
