name: Smoke Test

on:
  schedule:
    - cron: "0 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Test the layout hasn't changed and broken the gem
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path ./vendor/bundle
          bundle exec rspec -t smoke_test
